name: Create new release


on:
  repository_dispatch:
    types: [new-release]
  workflow_dispatch:


jobs:
  merge-develop:
    name: Merge irispie/develop into irispie-ce/master-ce
    runs-on: ubuntu-latest

    steps:
      - name: Checkout irispie-ce master-ce branch
        uses: actions/checkout@v4
        with:
          repository: IRIS-Solutions-Team/irispie-ce
          ref: master-ce
          token: ${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}
          path: irispie-ce
          fetch-depth: 0

      - name: Configure Git
        working-directory: irispie-ce
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local pull.rebase false
          git config --local merge.ours.driver true
          git config --local merge.theirs.driver "cp %B %A"

      - name: Mirror develop
        working-directory: irispie-ce
        run: |
          git fetch origin develop
          git switch develop
          git remote add irispie https://${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}@github.com/IRIS-Solutions-Team/irispie.git
          git pull irispie develop
          git push origin develop

      - name: Merge develop into master-ce
        working-directory: irispie-ce
        run: |
          git switch master-ce
          git merge develop
          git push origin master-ce


  create-release:
    name: Create tagged commit and release
    runs-on: ubuntu-latest
    needs: merge-develop

    steps:
      - name: Checkout irispie-ce master-ce branch
        uses: actions/checkout@v4
        with:
          repository: IRIS-Solutions-Team/irispie-ce
          ref: master-ce
          token: ${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}
          path: irispie-ce

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: irispie-ce
        run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: Configure Git
        working-directory: irispie-ce
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Change edition to 'ce' and commit
        working-directory: irispie-ce
        run: |
          python .github/workflows/make_edition.py --edition ce
          git add -u .
          git commit -m "Change edition to RE"

      - name: Get version tag
        id: get_version
        working-directory: irispie-ce
        run: |
          VERSION=$(python .github/workflows/print_version.py)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create and push tag
        env:
          version: ${{ steps.get_version.outputs.version }}
        working-directory: irispie-ce
        run: |
          git tag $version
          git push origin master-ce --tags

      - name: Create release
        id: create_release
        env:
          tag: ${{ steps.get_version.outputs.version }}
          # gh picks the token from GITHUB_TOKEN env variable automatically
          GITHUB_TOKEN: ${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}
        working-directory: irispie-ce
        run: |
            gh release create "$tag" \
              --title "Release $tag" \
              --notes ""

