# Needs a secret IRISPIE_ACTIONS_TOKEN_2025
# Needs a repository variable EDITION

name: Create new release


on:
  repository_dispatch:
    types: [new-release]
  workflow_dispatch:


jobs:
  merge-develop:
    name: Merge irispie/develop into irispie-edition/master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout irispie-edition/master branch
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}
          path: irispie-edition
          fetch-depth: 0

      - name: Configure Git
        working-directory: irispie-edition
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local pull.rebase false
          git config --local merge.ours.driver true
          git config --local merge.theirs.driver "cp %B %A"

      - name: Mirror develop
        working-directory: irispie-edition
        run: |
          git fetch origin develop
          git switch develop
          git remote add irispie https://${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}@github.com/IRIS-Solutions-Team/irispie.git
          git pull irispie develop
          git push origin develop

      - name: Merge develop into master
        working-directory: irispie-edition
        run: |
          git switch master
          git merge develop
          git push origin master


  create-release:
    name: Create tagged commit and release
    runs-on: ubuntu-latest
    needs: merge-develop

    steps:
      - name: Checkout irispie-edition/master branch
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}
          path: irispie-edition

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: irispie-edition
        run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: Configure Git
        working-directory: irispie-edition
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set correct edition
        env:
          EDITION: ${{ vars.EDITION }}
        working-directory: irispie-edition
        run: |
          python .github/workflows/make_edition.py --edition $EDITION
          git add -u .
          git commit -m "Set correct edition to $EDITION"

      - name: Get version tag
        id: get_version
        working-directory: irispie-edition
        run: |
          VERSION=$(python .github/workflows/print_version.py)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create and push tag
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        working-directory: irispie-edition
        run: |
          git tag $VERSION
          git push origin master --tags

      - name: Create release
        id: create_release
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          # gh picks the token from GITHUB_TOKEN env variable automatically
          GITHUB_TOKEN: ${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}
        working-directory: irispie-edition
        run: |
            gh release create "$VERSION" \
              --title "Release $VERSION" \
              --notes ""

