name: Placeholdder


on:
  workflow_dispatch:


jobs:
  placeholder:
    name: Placeholder job
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder step
        run: echo "This is a placeholder action"

