#
# Run tests using the irispie-tests repository
# This workflow can be run independently or called by other workflows
#

name: Test

on:
  # Allow manual triggering
  workflow_dispatch:
  
  # Allow being called by other workflows
  workflow_call:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout irispie/develop
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop
          path: irispie
          token: ${{ secrets.IRIS_SOLUTIONS_TEAM_TOKEN_2026 }}

      - name: Checkout irispie-tests/master
        uses: actions/checkout@v4
        with:
          repository: IRIS-Solutions-Team/irispie-tests
          fetch-depth: 1
          ref: master
          path: irispie-tests
          token: ${{ secrets.IRIS_SOLUTIONS_TEAM_TOKEN_2026 }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install -e irispie
          pip install pytest toml

      - name: Run tests
        working-directory: irispie-tests
        run: |
          pytest -ra -v @specs
