# Worflow to run tests, bump version, create tag and release, and notify edition
# repositories

name: Test and version

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout irispie/develop
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop
          path: irispie
          token: ${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}

      - name: Checkout irispie-tests/master
        uses: actions/checkout@v4
        with:
          repository: IRIS-Solutions-Team/irispie-tests
          fetch-depth: 1
          ref: master
          path: irispie-tests
          token: ${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -e irispie
          pip install pytest toml

      - name: Run tests
        working-directory: irispie-tests
        run: |
          pytest @specs


  version-bump:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump-version.outputs.new-version }}
      new-mmp: ${{ steps.bump-version.outputs.new-mmp }}

    steps:
      - name: Checkout irispie/develop
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop
          path: irispie
          token: ${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}
          repository: IRIS-Solutions-Team/irispie

      - name: Set up identity
        working-directory: irispie
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies for version bumping
        run: |
          pip install toml

      - name: Bump version in pyproject.toml
        id: bump-version
        working-directory: irispie
        run: |
          if ! [[ -e ./.release_type ]]; then
            echo "Cannot release without .release_type"
            exit 1
          fi
          RELEASE_TYPE=$(< ./.release_type)
          python ./.github/workflows/bump_version.py --release-type=$RELEASE_TYPE
          NEW_MMP=$(python ./.github/workflows/print_mmp.py)
          NEW_VERSION=$(python ./.github/workflows/print_version.py)
          echo "New version is $NEW_VERSION"
          echo "New MMP is $NEW_MMP"
          echo "new-mmp=$NEW_MMP" >> $GITHUB_OUTPUT
          echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT 

      - name: Commit and push new version to develop
        env:
            version: ${{ steps.bump-version.outputs.new-version }}
        working-directory: irispie
        run: |
          git switch develop
          git add ./pyproject.toml
          git rm .release_type
          git commit -m "Bump version to $version"
          git tag $version
          git push origin develop --tags

      - name: Create release
        id: create-release
        env:
          version: ${{ steps.bump-version.outputs.new-version }}
          # gh picks the token from GITHUB_TOKEN env variable automatically
          GITHUB_TOKEN: ${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}
        working-directory: irispie
        run: |
            gh release create "$version" \
              --title "Release $version" \
              --notes ""


  broadcast-release:
    needs: version-bump
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #repository: [irispie-ce, irispie-re, irispie-pe]
        repository: [irispie-re]
    env:
      new-mmp: ${{ needs.version-bump.outputs.new-mmp }}

    steps:
      - name: Repository dispatch to ${{ matrix.repository }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.IRISPIE_ACTIONS_TOKEN_2025 }}
          repository: IRIS-Solutions-Team/${{ matrix.repository }}
          event-type: new-release
          client-payload: |
            {
              "mmp": "${{ env.new-mmp }}"
            }

